### ISSUE TITLE
Enable adding PoRs by General Secretaries

### ISSUE THREAD

**Issue by ydidwania** [wncc/InstiApp#168]
In the long term, we'd like to give Edit Body permission for every Institute Body  to only `gsectech` and similar ldap ids. They will then have the option to add their subordinates .

All subordinate PoRs should be reset on April 1, when the next tenure starts

**Comment by pulsejet** [comment]
Backend already has this permission model, i.e. allowing adding roles of bodies. Probably need a better API for this though.
