### ISSUE TITLE
Notifications redirect bug with placement blog, internship blog

### ISSUE THREAD

**Issue by samjakes** [wncc/InstiApp#232]
**EDIT: My android version is 9.0 (Pie)**

Steps: 
Go to either of the blogs.
Press the "Notifications icon" i.e the bell
Press back on your phone
It doesn't redirect back to the blog

In the case of the InstiMap, it redirects back to the map, but the map fails to reload.

**Comment by pulsejet** [comment]
@unstablebrainiac something to do with the API calls not happening when popping the back stack. Pressing the back button to go to any of News, PT Blog, Map etc. fails to load from the API.
