### ISSUE TITLE
Suggestion to replace all material icons with their outlined versions

### ISSUE THREAD

**Issue by tastelessjolt** [wncc/InstiApp#236]
I'm suggesting to replace all material filled icons with their `outline`d icons. It might look better. 
https://material.io/tools/icons/?style=outline

And also in the settings page, the icons are in black, and I think grey icons like everywhere else would be better.

**Comment by pulsejet** [comment]
+1 for changing the black icons to grey; probably that's what's making the settings page look so out of place. As for using the outlined icons, I'd rather let designers decide, since there are bound to be split opinions on this.
