### ISSUE TITLE
searching something (let's say, a name) crashes on Android mobile app.

### ISSUE THREAD

**Issue by SiluPanda** [wncc/InstiApp#280]
While searching something on placement/internship blog, the app crashes.
It often slows down/freezes the browser upon doing the same on web app too.

Device used: For Mobile App: Motorola ; Android 6
                     For webApp: Firefox quantum on Ubuntu 18.04

**Comment by pulsejet** [comment]
@SiluPanda, can you provide more details about your hardware. I am unable to repro on any of my test devices. Also, are you running the latest versions of the apps?

**Comment by SiluPanda** [comment]
https://www.gsmarena.com/motorola_moto_e3_power-8337.php

may be it is a issue of the device as it is too old.

**Comment by pulsejet** [comment]
I'd like to think of any marshmallow device as supported, so let's investigate this further. Could you post you logcat of the crash for a debug build?

**Comment by unstablebrainiac** [comment]
Closing this due to lack of response from OP
